- name: Create swap space
  command: dd if=/dev/zero of=/swapfile bs=1M count=2048
  when: ansible_swaptotal_mb < 1

- name: Make swap
  command: mkswap /swapfile
  when: ansible_swaptotal_mb < 1

- name: Add to fstab
  action: lineinfile 
    dest=/etc/fstab 
    regexp="swapfile" 
    line="/swapfile swap swap defaults 0 0" 
    state=present
  when: ansible_swaptotal_mb < 1

- name: Turn swap on
  command: swapon -a
  when: ansible_swaptotal_mb < 1

- name: Set swapiness
  shell: echo 0 | sudo tee /proc/sys/vm/swappiness
  when: ansible_swaptotal_mb < 1