- name: apt update
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: install nginx
  apt:
    name: nginx
    state: latest
- name: add ppa
  apt_repository:
    validate_certs: no
    repo: 'ppa:ondrej/php'
    state: present
- name: inatall PHP 7.4
  apt:
    pkg:
    - php7.4-bcmath
    - php7.4-cli
    - php7.4-common
    - php7.4-curl
    - php7.4-gd
    - php7.4-imap
    - php7.4-intl
    - php7.4-mbstring
    - php7.4-mysql
    - php7.4-readline
    - php7.4-soap
    - php7.4-xml
    - php7.4-xmlrpc
    - php7.4-zip
    - php7.4-imagick
    - php7.4-fpm
- name: inatall PHP 8.1
  apt:
    pkg:
    - php8.1-bcmath
    - php8.1-cli
    - php8.1-common
    - php8.1-curl
    - php8.1-gd
    - php8.1-imap
    - php8.1-intl
    - php8.1-mbstring
    - php8.1-mysql
    - php8.1-readline
    - php8.1-soap
    - php8.1-xml
    - php8.1-xmlrpc
    - php8.1-zip
    - php8.1-imagick
    - composer
    - imagemagick
- name: install php-fpm
  apt:
    name: php8.1-fpm
    state: latest
- name: inatall PHP 8.2
  apt:
    pkg:
    - php8.2-bcmath
    - php8.2-cli
    - php8.2-common
    - php8.2-curl
    - php8.2-gd
    - php8.2-imap
    - php8.2-intl
    - php8.2-mbstring
    - php8.2-mysql
    - php8.2-readline
    - php8.2-soap
    - php8.2-xml
    - php8.2-xmlrpc
    - php8.2-zip
    - php8.2-imagick
    - php8.2-fpm
- name: install MariaDB
  apt:
    pkg:
    - mysql-client
    - mysql-server
- name: install automysqlbackup
  apt:
    name: automysqlbackup
    state: latest
- name: enable nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
- name: create directory /etc/nginx/serverok
  file:
    path: /etc/nginx/serverok
    state: directory
- name: nginx config
  get_url:
    url: https://raw.githubusercontent.com/serverok/server-setup/master/config/nginx/serverok/wp-fastcgi-cache.conf
    dest: /etc/nginx/serverok/wp-fastcgi-cache.conf
    mode: '0750'
- name: nginx config
  get_url:
    url: https://raw.githubusercontent.com/serverok/server-setup/master/config/nginx/conf.d/sok_cache.conf
    dest: /etc/nginx/conf.d/sok_cache.conf
    mode: '0750'
- name: enable mysql
  systemd:
    name: mysql
    state: started
    enabled: yes
- name: enable php-fpm
  systemd:
    name: php8.1-fpm
    state: started
    enabled: yes
- name: download update-php-ini
  get_url:
    url: https://raw.githubusercontent.com/serverok/server-setup/master/install/update-php-ini.sh
    dest: /usr/local/bin/update-php-ini
    mode: '0755'
- name: update php.ini
  command: /usr/local/bin/update-php-ini
- name: enable password authentication
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication no$'
    replace: 'PasswordAuthentication yes'
- name: restart ssh
  command: systemctl restart ssh
- name: add add-site script
  get_url:
    url: https://raw.githubusercontent.com/serverok/server-setup/master/tools/sok-nginx-add-site.py
    dest: /usr/local/bin/sok-site-add
    mode: '0755'
