---
- hosts: web
  remote_user: root
  become_method: sudo
  tasks:
    - name: apt update
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: install nginx
      apt:
        name: nginx
        state: latest
    - name: inatall php
      apt:
        pkg:
        - php7.4-bcmath
        - php7.4-cli
        - php7.4-common
        - php7.4-curl
        - php7.4-gd
        - php7.4-imap
        - php7.4-intl
        - php7.4-json
        - php7.4-mbstring
        - php7.4-mysql
        - php7.4-readline
        - php7.4-soap
        - php7.4-xml
        - php7.4-xmlrpc
        - php7.4-zip
        - composer
    - name: install php-fpm
      apt:
        name: php7.4-fpm
        state: latest
    - name: install MariaDB
      apt:
        pkg:
        - mariadb-client
        - mariadb-server
    - name: install automysqlbackup
      apt:
        name: automysqlbackup
        state: latest
    - name: enable nginx
      systemd:
        name: nginx
        state: started
        enabled: yes
    - name: enable mysql
      systemd:
        name: mysql
        state: started
        enabled: yes
    - name: enable php-fpm
      systemd:
        name: php7.4-fpm
        state: started
        enabled: yes
    - name: install monit
      apt:
        name: monit
        state: latest
    - name: enable nginx monitoring
      file:
        src: "/etc/monit/conf-available/nginx"
        dest: "/etc/monit/conf-enabled/nginx"
        state: link
    - name: enable mysql monitoring
      file:
        src: "/etc/monit/conf-available/mysql"
        dest: "/etc/monit/conf-enabled/mysql"
        state: link
    - name: enable monit
      systemd:
        name: monit
        state: started
        enabled: yes
    - name: download update-php-ini
      get_url:
        url: https://raw.githubusercontent.com/serverok/server-setup/master/install/update-php-ini.sh
        dest: /usr/local/bin/update-php-ini
        mode: '0755'
    - name: update php.ini
      command: /usr/local/bin/update-php-ini
    - name: enable password authentication
      replace:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication no$'
        replace: 'PasswordAuthentication yes'
    - name: restart ssh
      command: systemctl restart ssh
    - name: add add-site script
      copy:
        src: /home/boby/www/projects/server-setup/ubuntu/add-site.py
        dest: /usr/local/bin/sok-site-add
        owner: root
        group: root
        mode: '0755'
