---
- hosts: web
  remote_user: root
  become_method: sudo
  tasks:
    - name: apt update
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: install apache
      apt:
        pkg:
        - apache2
        - libapache2-mod-ruid2
    - name: update mutex
      replace:
        path: /etc/apache2/apache2.conf
        regexp: '^#Mutex file:..APACHE_LOCK_DIR. default$'
        replace: 'Mutex posixsem'
    - name: install software-properties-common
      apt:  
        pkg:
        - software-properties-common
    - name: add ppa
      apt_repository:
        repo: 'ppa:ondrej/php'
    - name: inatall php
      apt:
        pkg:
        - php7.4
        - php7.4-bcmath
        - php7.4-bz2
        - php7.4-cgi
        - php7.4-cli
        - php7.4-common
        - php7.4-curl
        - php7.4-dba
        - php7.4-dev
        - php7.4-enchant
        - php7.4-gd
        - php7.4-gmp
        - php7.4-imap
        - php7.4-intl
        - php7.4-json
        - php7.4-mbstring
        - php7.4-mysql
        - php7.4-opcache
        - php7.4-pgsql
        - php7.4-pspell
        - php7.4-readline
        - php7.4-soap
        - php7.4-sqlite3
        - php7.4-sybase
        - php7.4-tidy
        - php7.4-xml
        - php7.4-xmlrpc
        - php7.4-zip
        - php7.4-xsl
        - php7.4-gmp
        - php7.4-imagick
        - composer
        - libapache2-mod-php7.4
        - imagemagick
    - name: enable apache modules
      command: a2enmod rewrite ssl php7.4 headers
    - name: disable mod_autoindex
      command: a2dismod autoindex -f
    - name: enable apache2 service
      systemd:
        name: apache2
        state: started
        enabled: yes
    - name: install mysql server
      apt:
        pkg:
        - mariadb-server
    - name: enable mysql server
      systemd:
        name: mysql
        state: started
        enabled: yes
    - name: set postfix hostname
      debconf:
        name=postifx
        question="postfix/mailname"
        value="{{ inventory_hostname }}"
        vtype="string"
    - name: set postfix as internet site
      debconf:
        name=postfix
        question="postfix/main_mailer_type"
        value="'Internet Site'"
        vtype="string"
    - name: install postfix
      apt:
        name: postfix
        state: present
    - name: install automysqlbackup
      apt:
        name: automysqlbackup
        state: present
